export default {
    // NAVIGATION STACKS
    AUTH_STACK : 'AUTH_STACK',
    MAIN_STACK : 'MAIN_STACK',

    // SCREENS
    LOGIN_SCREEN        : 'LOGIN_SCREEN',
    REGISTRATION_SCREEN : 'REGISTRATION_SCREEN',
    PROFILE_EDIT_SCREEN : 'PROFILE_EDIT_SCREEN',
    PROFILE_SCREEN      : 'PROFILE_SCREEN'
};
